spring:
  datasource:
    username: bxiit
    password: password
    url: jdbc:postgresql://localhost:5454/auth-db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8888
token:
  signing:
    key: asdqwertyasdqwertyasdqwertyasdqwertyasdqwertyasdqwertyasdqwerty
logging:
  level:
    org.zalando.logbook: trace
logbook:
  obfuscate:
    json-body-fields: password